# Multi Stage pipeline
name: Terraform Multi Stage Pipeline
trigger: none

pool: RohtasPool

stages:
  - stage: TerraformInstall
    displayName: "terraform install stage"
    jobs:
    - job: TerraformInstallJob
      displayName: "Terrform Install job"
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
    
  - stage: TerraformInitPlan
    displayName: "Terraform Init Plan stage"
    dependsOn: TerraformInstall
    jobs:
      - job: TerraformInitPlanJob
        displayName: "Terraform Init Plan job"
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/prod'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'svc-connection-robinson15kumar'
            backendAzureRmResourceGroupName: 'rg-robinson'
            backendAzureRmStorageAccountName: 'robinteststorage3'
            backendAzureRmContainerName: 'mycontainer'
            backendAzureRmKey: 'dev.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/prod'
            environmentServiceNameAzureRM: 'svc-connection-robinson15kumar'

  - stage: TerraformInitApply
    displayName: "Terraform Init Apply"
    jobs:
      - job: TerraformInitApplyJob
        displayName: "Terraform Init Apply job"
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/prod'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'svc-connection-robinson15kumar'
            backendAzureRmResourceGroupName: 'rg-robinson'
            backendAzureRmStorageAccountName: 'robinteststorage3'
            backendAzureRmContainerName: 'mycontainer'
            backendAzureRmKey: 'dev.tfstate'   
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/prod'
            environmentServiceNameAzureRM: 'svc-connection-robinson15kumar'